global:
  scrape_interval:     2s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['34.247.193.71:8428']
  - job_name: 'nodes'
    static_configs:
      - targets: ['34.247.193.71:9100','18.200.151.27:9100','34.241.243.11:9100','34.253.157.74:9100','34.254.118.109:9100','52.209.217.82:9100','52.215.254.138:9100','52.215.41.150:9100','	52.48.18.207:9100','99.81.190.96:9100','34.241.45.95:9100']
