global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'node'
    static_configs:
    - targets: ['34.252.219.244:9100']
    - targets: ['54.216.104.5:9100']
    - targets: ['3.250.221.216:9100']
    - targets: ['34.252.219.244:9100']
