global:
  scrape_interval:     2s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'node'
    static_configs:
      - targets: ['52.213.123.147:9100','52.210.28.139:9100','99.81.238.248:9100','34.246.100.160:9100','3.248.159.70:9100','108.128.145.100:9100','34.250.120.140:9100','34.255.220.86:9100','52.208.78.108:9100','52.30.120.11:9100']
